language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
os:
  - linux
  - osx
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -n test
  - source activate test
  - conda build .
env:
  global:
    secure: UZIjUCZh1hdPcTCfaDi8/bwqZGPh1W0u+cC6o/1FZ6zjwVhHonlB9eD8SJ4FsMnxWzpG/823HqlIr4e+y1rRpZnpWUNqilaUhrBpwqyBSO7/L1v+d9k1AmjG2qLUWyptAvvPBNfmjlmi3fAH7SLXzj0xcT5lJVtzv4/Kkm21Dkc2fH3ABaxMlqted7rlAbyB1ZTZ7QkkFdDQGWdvpRBWlm995JOF7keEeFz2+NzqWihMCABk6E8HJLTrYDwu9rNqkBnIEYOAYyPMivJdrPk5hF0jFq+/1yWtvrz3Lubc5JKONrV8RL+ShLHJmssn0jLlIMT5i1lTZGUylu5k2eoFappk+Njq0wCImw9iPH3LaAvITXhiVM1R97GnRYWtjOScEMTns48qrG2a73mzvEl+DqMLpsTKuiC0ibffEK6hknguDT+s6Ggldj3opPxIjfQ9Me3H/h3UkBNGUBekMpdDDXNstvUgwyWQSGLxj4WXmkr0JLJhXczeHLJaylDc+QrYA7k4yn+pGktQLPJaPQvHd9sGeRHXURRvBCYEp9OvKs37VeoFpfvW9ljvev/wHXvvt9zhDcocSfw3QpcoOPGJnoZH01HAoWRcuAmEbZxatePK1wWdxJNNxQR+Dvx28Hz5nwOwrzGiR4tXi1IT69eIoGZfYVzqmjzhvNLs6CRBIqQ=
