package:
  name: dsk
  version: "1.6906"

build:
  number: 1

requirements:
  build:
    - cmake
    - gcc

source:
  url: http://minia.genouest.org/dsk/dsk-1.6906.tar.gz
  md5: 08e392f93ed66692adb62aa5df972db6

