package:
  name: dsk
  version: "2.1.0"

build:
  number: 1

source:
  fn: dsk-2.1.0-Source.tar.gz
  url: http://gatb-tools.gforge.inria.fr/versions/src/dsk-2.1.0-Source.tar.gz
  md5: 767fcb2b1137b55c6c17ef474656a1f7

requirements:
  build:
    - cmake
    - gcc

test:
  commands:
    - dsk 2>&1 | grep 'dsk options'
    - dsk2ascii 2>&1 | grep 'dsk2ascii options'
    
